config/routes.rb
Rails.application.routes.draw do
  get 'about_us/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  get 'welcome/index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'signout', to: 'sessions#destroy', as: 'logout'
  
  resources :articles do
    resources :comments
  end
  
  root 'welcome#index'
  
  root to: "photos#index"
  resources :photos
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    
    has_one :photo
    
    has_many :comments, dependent: :destroy

    validates :title, presence: true, length: { minimum: 5 }

    validates :text, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/photo.rb
class Photo < ApplicationRecord
    has_attached_file :image
    
    do_not_validate_attachment_file_type :image
    
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    before_save { self.email = email.downcase }
    
    validates :name,
        presence: true,
        length: { maximum: 12 }
    
    validates :email,
        presence: true,
        length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
        
    validates :password,
        presence: true,
        length: { minimum: 6 },
        :format => {:with => /\A(?=.*[a-zA-Z])(?=.*[0-9]).{6,}\Z/, message: "must be at least 6 characters and include one number and one letter."}
        
    has_secure_password
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    def index
        @articles = Article.all
    end
        
    def show
        @article = Article.find(params[:id])
        @article.view ||= 0
        abc = @article.view += 1
        @article.update_attribute "view", abc
    end

    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        
        if @article.save
    
        redirect_to @article
        else
        render 'new'
        end
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
        redirect_to @article
        else
        render 'edit'
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end
end

private
def article_params
    params.require(:article).permit(:title, :text)
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
        
    end
    
    def edit
        @article = Article.find(params[:article_id])
        @comment = Comment.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:article_id])
        @comment = Comment.find(params[:id])
        if @comment.update(comment_params)
        redirect_to article_path(@article)
        else
        render 'edit'
        end
    end
        
    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end
    
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end 

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    
def index
        @photos = Photo.order('created_at')
end

def new
    @photo = Photo.new
end

    
 def create
    @photo = Photo.new(photo_params)
    if @photo.save
        flash[:notice] = "Added photo"
        redirect_to photos_path
    else
        flash[:alert] = "Error did not save photo"
        render :new
    end 
 end
 
 
def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
        flash[:notice] = "deleted photo"
        redirect_to photos_path
    else
        flash[:alert] = "error deleting photo"
    end
end     

private
def photo_params
    params.require(:photo).permit(:title, :image)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about_us/index.html.erb
<h1>About Us!</h1>

<p>Levar Fredericks</p>
<p>Sophomore computer science major, at UNCC, pursuing a data science career. 
Due to my love of sports and exercise, my goal is to be in a position to make 
analytical decisions that will benefit athletes.</p>

<br>

<p>Logan Carpenter</p>
<p>My name is Logan, and in the future, I want to be able to do large scale Data
Science, same as my concentration, and build online creations for business 
owners, host servers, and do a bit of cyber security.</p>

<br>

<p>Isaac Damiani</p>
<p>I am an undergraduate student at the University of North Carolina at 
Charlotte studying Computer Science with a concentration on Software 
Engineering. I will be graduating this Spring semester of 2020 and starting the 
next chapter in my life. I have been honored to have worked on this blog project
with my fellow group members throughout the semester. Although we came across 
many obstacles and unfortunate situations through the semester, we were able to 
overcome everything that came at us.</p>

<br>

<p>Brady Ennis</p>
<p>I'm Brady Ennis. I'm a CS major concentrating in web and application 
development who works for Novant as a student developer on the side.</p>

<br>

<p>Jeremy Dannemiller</p>
<p>My name is Jeremy dannemiller I am 38 studying computer science in hope to be
able to understand multiple aspects of the computer world so I can practice 
fixing problems for a person or company.</p>

<%= link_to 'Back', root_path %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  
  
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<p></p>

<%= link_to 'New article', new_article_path %>

<p></p>
<%= link_to 'Upload photo', new_photo_path %>

<p></p>

<%= link_to 'Back', root_path %>


<br /><br /><br />

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Author</th>
    <th>Posted</th>
    <th>Views</th>
    

  </tr>
     <%@articles.each_with_index do |article, index| %>

    <% end %>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>

      <td><% if article.user %>
            <%= article.user.name %>
          <% end %>
      </td>
        
      <td><%= article.created_at %></td>

      <td><%= article.view %></td>
      
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy',
                                article_path(article),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

    
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for :article, url: articles_path do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @article.text %>
</p>
<%= social_share_button_tag(@article.title,
                    :image => "https://raw.github.com/vkulpa/social-share-button/master/lib/assets/images/sprites/social-share-button/tumblr.png",
                    :'data-type' => 'photo',
                    :url => "https://9685e9247ad04c1dbc0951361b0a24b1.vfs.cloud9.us-east-2.amazonaws.com/articles/1#",
                    :'data-source' => "https://raw.github.com/vkulpa/social-share-button/master/lib/assets/images/sprites/social-share-button/tumblr.png", :'data-type' => 'photo',) %>

<h2 style="color:#FDB927;font-family: Verdana;">Comments:</h2>
<%= render @article.comments %>

<br><br>
<h2 style="color:#FDB927;font-family: Verdana;">Add a comment:</h2>

<%= render 'comments/form' %>

<%= link_to 'Article List', articles_path %>

app/views/comments/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  
  <p>
<%= link_to 'Edit', edit_article_comment_path(comment.article, comment) %>
<%= link_to 'Destroy', [comment.article, comment],
      method: :delete,
      data: { confirm: 'Are you sure?' } %>
 </p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>
 
<%= form_for([@article, @comment]) do |f| %>
 
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") %> prohibited
        this comment from being saved:
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/photos/index.html.erb
<div class="page-header"><h1>Photos</h1></div>

<div class = "media">
    <%= @photos.each do |photo| %>
    <div class = "media-left">
        <!-- Renders image -->
        <%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
        <!-- Button to delete image -->
        <%= link_to 'Remove', photo_path(photo), class: 'btn btn-danger', method: :delete, data: {confirm:'Are you sure'} %>
        
    </div>
    <div class = "media-body">
        <h4 class = "media-heading"><%= photo.title %></h4>
    </div>
    <% end %>
    
    <%= link_to 'Back', new_photo_path %>

</div>

app/views/photos/new.html.erb
<div class = "page-header"><h1>Upload Photo</h1></div>

<%= form_for @photo, html: {multipart: true } do |f| %>
    <% if @photo.errors.any? %>
    <div id = "error_explanation">
        <h2>
            <%= "#{pluralize(@photo.errors.count, "error")} photo could not be saved:"%>
        </h2>
        <ul>
            <% @photo.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
            <% end %>
        </ul>
    </div>
    <% end %>
    
    <div class = "form-group">
        <%= f.label :title %>
        <%= text_field :title, class: 'form-control' %>
    </div>
    
    <div class = "form_group">
        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control' %>
    </div>
    
    <div class="form-group">
        <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
    </div>
<% end %>

 <div>
     <%= link_to 'Photo collection', photos_path %>
<%= link_to 'Back', articles_path %>
 </div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Hello, Blog App User!</h1>

<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'About Us', controller: 'about_us' %>

<p>
    <% if current_user %>
        Logged in as <%= current_user.name %>
        <%= link_to "Log Out", logout_path %>
    <% else %>
        <%= link_to "Sign Up", signup_path %>
        <%= link_to "Login", login_path %>
    <% end %>
</p>